baseURL = '/'
languageCode = 'en-us'
title = 'Electronics engineering at Polimi ğŸ“'
theme = 'tito-bearblog'
disableKinds = ["taxonomy"]

enableEmoji = true

[params]
favicon = "favicon.ico"
description = "Appunti degli studenti di ingegneria elettronica al Politecnico di Milano\nNotes from students on electronics engineering at Politecnico di Milano"

